CWD = '/home/twister/Documents/caras_xiao/RecipeGeneration'

ING_LIST_PATH = CWD + '/data_processing/data/det_ingrs_raw.json'
ING_LIST_SMALL_PATH = CWD + '/data_processing/data/det_ingrs_small.json'
RECIPE_PATH = CWD + '/data_processing/data/layer1.json'
RECIPE_PATH_SMALL = CWD + '/data_processing/data/layer1_small.json'
RECIPE_BATCH_PATH = CWD + '/data_processing/data/recipe_batches'
ING_BATCH_PATH = CWD + '/data_processing/data/ing_batches'
ING = 'ingredients'
ACT = 'actions'
